# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cea8edfae26816cfb40f36c2553b2639dc49f0cafb808e6be6093fadb0d6aa28a19f2534148b3cf3ef478c35fe53c963e025ec713b4b874311046b002f56871

test:
  secret_key_base: d8e97f0e9de2b42ffa60a890b09395cf1f3ba02e6cba0c6cddc2a695479ee6571fd0a664b3a2a6bd608e5af4c5daf69d49505171b3c46921bde2777e40800cf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
